ViewModels/HomeViewModel.cs
using Shop.Data.Shoes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Product> favGoods { get; set; }
    }
}

ViewModels/ShoesListviewModels.cs
using Shop.Data.Shoes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class ShoesListviewModels
    {
        public IEnumerable<Product> AllShoes { get; set; }
        public string shoesCategory { get; set; }
    }
}

ViewModels/ShopCartViewModel.cs
using Shop.Data.Shoes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class ShopCartViewModel
    {public ShopCart shopCart { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class HomeController: Controller
    {
        private readonly IAllShoes _shoesRep;
        
        public HomeController(IAllShoes shoesRep)
        {
            _shoesRep = shoesRep;

        }
        public ViewResult Index()
        {
            var homeProducts = new HomeViewModel
            {
                favGoods = _shoesRep.getFavGoods
            };
            return View(homeProducts);
        }
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Shoes;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }
        public IActionResult Checkout()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.listShopItems = shopCart.GetShopItems();
            if (shopCart.listShopItems.Count == 0)
            {
                ModelState.AddModelError("","Товари у кошику відсутні");
            }
            if (ModelState.IsValid)
            {
                allOrders.createOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order);
        }
        public IActionResult Complete()
        {
            ViewBag.Message = "Замовлення опрацьовано";
            return View();
        }
    }

    
}

Controllers/ShoesController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Shoes;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class ShoesController : Controller
    {
        private readonly IAllShoes _allShoes;
        private readonly IShoesCategory _allCategory;

        public ShoesController(IAllShoes iallShoes, IShoesCategory ishoesCat)
        {
            _allShoes = iallShoes;
            _allCategory = ishoesCat;
        }

        [Route("Shoes/List")]
        [Route("Shoes/List/{category}")]

        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Product> products = null;
            string shoesCategory = "";

            if (string.IsNullOrEmpty(category))
            {
                products = _allShoes.Shoes.OrderBy(i => i.id);
            }
            else if (string.Equals("кросівки", category, StringComparison.OrdinalIgnoreCase))
            {
                products = _allShoes.Shoes.Where(i => i.Category.categoryName.Equals("Крoсівки")).OrderBy(i => i.id);
                shoesCategory = "Крoсівки";
            }
            else if (string.Equals("черевики", category, StringComparison.OrdinalIgnoreCase))
            {
                products = _allShoes.Shoes.Where(i => i.Category.categoryName.Equals("Черевики")).OrderBy(i => i.id);
                shoesCategory = "Черевики";
            }
       
            var shoesObj = new ShoesListviewModels
            {
                AllShoes = products,
                shoesCategory = shoesCategory,
            };


            ViewBag.Title = "Сторінка з брендами-";
            ShoesListviewModels obj = new ShoesListviewModels();
            obj.AllShoes = _allShoes.Shoes;
            obj.shoesCategory = "Бренди";

            return View(shoesObj);
        }


    }
}

Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Repository;
using Shop.Data.Shoes;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class ShopCartController:Controller
    {
        private readonly IAllShoes _shoesRep;
        private readonly ShopCart _shopCart;

        public ShopCartController(ShoesRepository shoesRep, ShopCart shopCart)
        {
            _shoesRep = shoesRep;
            _shopCart = shopCart;

        }
        public ViewResult Index()
        {
            var items = _shopCart.GetShopItems();
            _shopCart.listShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };
            return View(); 
        } 

        public RedirectToActionResult addTocart(int id)
        {
            var item = _shoesRep.Shoes.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }

            return RedirectToAction("Index");
        }

    }
}

Views/Home/Index.cshtml
@model HomeViewModel
<h1> Кращі моделі</h1>
<div class="row mt -5 mb-2">
    @{
        foreach (Product product in Model.favGoods)
        {
            @Html.Partial("AllShoes", product)
        }
    }
</div>

Views/Order/Checkout.cshtml
@model Order
    <div class="row">
        <h3> Оформлення замовлення</h3>
        <form asp-action="Checkout" method="post" class="form-horisontal">
            <div class="form-group">
                <label asp-for="name"></label>
                <div class="col-md-5">
                    <input asp-for="name" class="form-control" />
                    <span asp-validation-for="name" class="text-danger"></span>
                </div>
            </div>

        </form>
        <form asp-action="Checkout" method="post" class="form-horisontal">
            <div class="form-group">
                <label asp-for="surname"></label>
                <div class="col-md-5">
                    <input asp-for="surname" class="form-control" />
                    <span asp-validation-for="surname" class="text-danger"></span>
                </div>
            </div>

        </form><form asp-action="Checkout" method="post" class="form-horisontal">
            <div class="form-group">
                <label asp-for="adress"></label>
                <div class="col-md-5">
                    <input asp-for="adress" class="form-control" />
                    <span asp-validation-for="adress" class="text-danger"></span>
                </div>
            </div>

        </form><form asp-action="Checkout" method="post" class="form-horisontal">
            <div class="form-group">
                <label asp-for="phone"></label>
                <div class="col-md-5">
                    <input asp-for="phone" class="form-control" />
                    <span asp-validation-for="phone" class="text-danger"></span>
                </div>
            </div>

        </form>
        form asp-action="Checkout" method="post" class="form-horisontal">
        <div class="form-group">
            <label asp-for="email"></label>
            <div class="col-md-5">
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <input class="bth bth-success" type="submit" value="Здійснити замовлення" />
        </div>
    </div>

Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Views/Shared/AllShoes.cshtml
@model Shop.Data.Shoes.Product

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.name" />
    <h2> @Model.name</h2>
    <h2> @Model.shortDesc</h2>
    <p>Ціна: @Model.price.ToString("c") </p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="5">Додати в кошик</a></p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap-grid.min.css.map" rel="stylesheet" type="text/css" />
   <link href="~/css/style.css" rel="stylesheet"type="text/css"/>
</head>
<body>
    <header>
       <nav class="navbar navbar-expand-md navbar-dark bg-dark">
           <a class="navbar-brand" href="#"></a>
           <button class="navbar-toggler" type="button" data-target="#navbarCollapse" aria-controls="navbarCollapse">
               <span class="navbar-toggler-icon"></span>
           </button>
           <div class="collapse navbar-colapse" id=" navbarCollapse">
               <ul class="navbar-nav mr-auto">
                   <li class="nav-item active">
                       <a class="nav-link" asp-controller="Home" asp-action="Index">Головна</a>
                   </li>
                   <li class="nav-item">
                       <a class="nav-link" href="/Shoes/List">Взуття</a>
                   </li>
                   <li class="nav-item">
                       <a class="nav-link" href="/Shoes/List/boots">Черевики</a>
                   </li>
                   <li class="nav-item">
                   <a class="nav-link" href="/Shoes/List/kross">Кросівки</a>
                   </li>
                   <li class="nav-item">
                       <a class="nav-link" href="/ShopCart/">Корзина</a>
                   </li>
               </ul>
               <form class="form-inline mt-2 mt-md-0">
                   <input class="form-control mr-sm-2" type="text" placeholder="Пошук" aria-label="Search" />
                   <button class="bth bth-outline-success my-2 my-sm-0" type="submit">Пошук</button>
               </form>
           </div>
       </nav>
    </header>
    <div class="container d-flex flex-column flex-md-row justify-content-between">
        <a class="py-2" href="#" aria-label="Product">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mx-auto" role="img" viewBox="0 0 24 24" focusable="false"><title>Product</title><circle cx="12" cy="12" r="10"></circle><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"></path></svg>
        </a>
        <a class="py-2 d-none d-md-inline-block" href="#">Tour</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Product</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Features</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Enterprise</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Support</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Pricing</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Cart</a>
    </div>
    <script src="~/js/bootstrap.min.js.map"></script>
</body>
</html>

Views/Shoes/List.cshtml
<h1> Усі бренди</h1>
<h2>@Model.shoessCategory</h2>
<div class="row mt -5 mb-2">
    @{
        foreach (Product product in Model.allShoes)
        {
            @Html.Partial("AllShoes", product)
        }
    }
</div>

Views/ShopCart/Index.cshtml
@model ShopCartViewModel
<div class="container">
    @foreach (var el in Model.shopCart.listShopItems)
    {
        <div class="alert alert-warning mt-3">
            <b>Бренд:</b>@el.product.name<br/>
            <b>Ціна:</b> @el.product.price.ToString("c")
        </div>
    }

    <hr />
    <a class="bth bth-danger" asp-controller="Order" asp-action="Checkout">Сплатити</a>

</div>